/**
 * MIL-Correspondence-Format
 * JSSDM 2022 Military Abbreviations Dataset
 * Developed by: xam, 72 FCC
 */

const MIL_ABBREVIATIONS = {
    // A
    "abbreviate": "abbr",
    "above mean sea level": "AMSL",
    "above water warfare": "AWW",
    "absent without leave": "AWOL",
    "abstract of evidence": "A of E",
    "accommodation": "accn",
    "account": "acct",
    "accounting unit": "AU",
    "acknowledge": "ack",
    "action": "act",
    "action information organization": "AIO",
    "actual time of arrival": "ATA",
    "additional": "addl",
    "address": "adds",
    "address indicating group": "AIG",
    "adjutant": "adjt",
    "administer": "admin",
    "administration": "admin",
    "administrative": "admin",
    "administrative control": "ADCON",
    "administration and logistics": "A&L",
    "administrative order": "AdminO",
    "advance": "adv",
    "advance trade training": "ATT",
    "advantage": "advtg",
    "after action review": "AAR",
    "air command operations centre": "ACOC",
    "air control team": "ACT",
    "air defence artillery": "ADA",
    "air defence control centre": "ADCC",
    "air defence commander": "ADC",
    "air defence clearance": "ADC",
    "aid-de-camp": "ADC",
    "air defence plan": "ADP",
    "air defence exercise": "ADEX",
    "air defence ground environment": "ADGE",
    "air defence identification zone": "ADIZ",
    "air defence notification centre": "ADNC",
    "air defence operations centre": "ADOC",
    "air defence weapon system": "ADWS",
    "air force doctrine document": "AFDD",
    "air force instruction": "AFI",
    "air force letter": "AFL",
    "air force order": "AFO",
    "air intelligence preparation of the battle space": "AIPB",
    "air liaison net": "ALN",
    "air liaison officer": "ALO",
    "air operations command centre": "AOCC",
    "air operation directive": "AOD",
    "air operations plan": "AOP",
    "area of operation": "AOP",
    "air operations planning process": "AOPP",
    "air raid precaution": "ARP",
    "air raid reporting control ship": "ARRCS",
    "air support operations centre": "ASOC",
    "air surveillance radar": "ASR",
    "airspace control": "ASCON",
    "airspace control authority": "ACA",
    "airspace control measures": "ACM",
    "airspace control order": "ACO",
    "airspace control plan": "ACP",
    "air control post": "ACP",
    "allied communications publication": "ACP",
    "air tasking order": "ATO",
    "air to air guided weapon": "AAGW",
    "air to air missile": "AAM",
    "guided missile": "AAGM",
    "guided weapon": "AAGW",
    "air to air refuelling": "AAR",
    "air to surface guided weapon": "ASGW",
    "air to surface missile": "ASM",
    "air traffic control": "ATC",
    "air traffic control centre": "ATCC",
    "airborne early warning": "AEW",
    "airborne warning and control": "AWACS",
    "aircraft": "ac",
    "aircraft accident investigation": "AAI",
    "aircraft establishment": "AE",
    "aircraft maintenance manual": "AMM",
    "aircraft on ground": "AOG",
    "airfield": "airfd",
    "airhead": "ahd",
    "all up weight": "AUW",
    "allocate": "alloc",
    "allotment": "alot",
    "allowance": "allce",
    "alter course": "a/c",
    "alternate": "altn",
    "alternative supply route": "ASR",
    "altitude": "alt",
    "ambulance": "amb",
    "amendment": "amdt",
    "ammunition": "ammo",
    "amphibious": "amph",
    "amphibious beach unit": "ABU",
    "amphibious task force": "ATF",
    "annex": "anx",
    "annual confidential report": "ACR",
    "annual performance report": "APR",
    "annual training grant": "ATG",
    "answer": "ans",
    "anti-tank": "Atk",
    "anti-aircraft": "AA",
    "anti aircraft artillery": "AAA",
    "anti-aircraft defence commander": "AADC",
    "anti-personnel": "Apers",
    "anti-tank guided missile": "ATGM",
    "anti-tank guided weapon": "ATGW",
    "anti-tank missile": "ATM",
    "anti-air warfare": "AAW",
    "anti-air warfare coordinator": "AAWC",
    "anti-radiation missile": "ARM",
    "anti-ship missile": "ASM",
    "anti-ship missile defence": "ASMD",
    "anti-submarine warfare": "ASW",
    "anti surface force operations": "ASFO",
    "anti-surface-vessel warfare": "ASVW",
    "anti-surface warfare": "ASuW",
    "appendix": "appx",
    "appoint": "appt",
    "appreciate": "aprc",
    "approach": "app",
    "application": "appl",
    "applications": "appl",
    "approximate": "approx",
    "area defence missile system": "ADMS",
    "area finance controller": "AFC",
    "area of interest": "AOI",
    "area maritime headquarters": "AMHQ",
    "armament": "armt",
    "armed forces": "AF",
    "armed forces division": "AFD",
    "armed forces medical stores depot": "AFMSD",
    "armed forces war course": "AFWC",
    "armour": "armr",
    "armour piercing discarding sabot": "APDS",
    "armour piercing fin stabilized discarding sabot": "APFSDS",
    "armour piercing incendiary": "API",
    "armoured": "armd",
    "armoured command vehicle": "ACV",
    "armoured fighting vehicle": "AFV",
    "armoured personnel carrier": "APC",
    "armoured recovery vehicle": "ARV",
    "armoured vehicle launched bridge": "AVLB",
    "army air corps": "AAC",
    "army aviation unit": "AAU",
    "army doctrinal publication": "ADP",
    "army dress regulations": "ADR",
    "army headquarters": "AHQ",
    "army post office": "APO",
    "army security unit": "ASU",
    "army sports control board": "ASCB",
    "army training and doctrine command": "ARTDOC",
    "army training note": "ATN",
    "army training manual": "ATM",
    "army training publication": "ATP",
    "arrange": "arng",
    "arrive": "arr",
    "article in use": "A in U",
    "artillery": "arty",
    "artillery course shooting": "ACS",
    "as soon as possible": "ASP",
    "assailability": "asl",
    "assault": "aslt",
    "assault ship": "LPD",
    "assembly": "assy",
    "assembly area": "Assy A",
    "assign": "asg",
    "assist": "asst",
    "assistant engineer": "AE",
    "assistant garrison engineer": "AGE",
    "asymmetric warfare": "AW",
    "attach": "att",
    "attack": "attk",
    "attend": "atnd",
    "attention": "attn",
    "authenticate": "authen",
    "attack helicopter": "AH",
    "automated air tasking order": "AATO",
    "authorized proportion": "AP",
    "authorize": "auth",
    "automatic direction finder": "ADF",
    "auxiliary": "aux",
    "auxiliary effort": "AE",
    "auxiliary gathering intelligence": "AGI",
    "auxiliary power unit": "APU",
    "avenue of approach": "AA",
    "average": "avg",
    "aviation": "avn",
    "aviation gasoline": "AVGAS",
    "aviation oil": "AVOIL",
    "axis of advance": "A of A",
    "azimuth": "az",

    // B
    "back loading point": "BLP",
    "backload": "bkld",
    "balance": "bal",
    "bangladesh air force": "BAF",
    "bangladesh armed services board": "BASB",
    "bangladesh army": "BA",
    "bangladesh army order": "BAO",
    "bangladesh coast guard": "BCG",
    "bangladesh diesel plant": "BDP",
    "bangladesh infantry": "BI",
    "bangladesh infantry regiment": "BIR",
    "bangladesh institute of maritime research and development": "BIMRAD",
    "bangladesh machine tools factory": "BMTF",
    "bangladesh national authority for chemical weapons convention": "BNACWC",
    "bangladesh national cadet corps": "BNCC",
    "bangladesh naval armament depot": "BNAD",
    "bangladesh navy": "BN",
    "bangladesh navy floating crane": "BNFC",
    "bangladesh navy floating dock": "BNFD",
    "bangladesh navy hydrographic and oceanographic centre": "BNHOC",
    "bangladesh navy ship": "BNS",
    "bangladesh navy sports control board": "BNSCB",
    "bangladesh navy tug": "BNT",
    "bangladesh ordnance factory": "BOF",
    "barrack": "bk",
    "base headquarters": "BHQ",
    "base supply depot": "BSD",
    "bangladesh university of professionals": "BUP",
    "bangabandhu sheikh mujibur rahman maritime university": "BSMRMU",
    "base workshop": "Bwksp",
    "basic ordering agreement": "BOA",
    "basic map reading": "BMR",
    "basic trade training": "BTT",
    "battalion": "bn",
    "battery": "bty",
    "battery command post": "BCP",
    "battle": "btl",
    "battlefield operating system": "BOS",
    "battlefield synchronization matrix": "BSM",
    "battle group": "BG",
    "battle inoculation": "BI",
    "battlefield air interdiction": "BAI",
    "beachhead": "bhd",
    "beacon": "bcn",
    "bearing": "bg",
    "beyond economic repair": "BER",
    "beyond local repair": "BLR",
    "beyond visual range": "BVR",
    "bibliography": "bib",
    "biological warfare": "BW",
    "binocular": "Bino",
    "bir bikram": "BB",
    "bir protik": "BP",
    "bir srestha": "BS",
    "bir utttam": "BU",
    "bivouac": "biv",
    "board of enquiry": "BOE",
    "board of inquiry": "BOI",
    "board of officers": "B of O",
    "boatswain": "BOS'N",
    "bomber": "B",
    "bombing": "Bx",
    "bombing report": "BOMBREP",
    "border guard bangladesh": "BGB",
    "boundary": "bdry",
    "branch recruiting unit": "BRU",
    "break clean line": "BCL",
    "break up shot": "BUS",
    "bridgehead": "brH",
    "brigade": "bde",
    "broadcast": "bro",
    "budget": "bgt",
    "built up area": "BUA",
    "bulk breaking point": "BBP",
    "butchery": "bchy",
    "build-operate-transfer": "BOT",

    // C
    "cadet": "cdt",
    "calculate": "cal",
    "calibrate": "calb",
    "camouflage": "cam",
    "camouflage and concealment": "C/C",
    "canalize": "cnz",
    "cantonment executive officer": "CEO",
    "canteen stores department": "CSD",
    "cantonment": "cantt",
    "capability": "cap",
    "capture": "capr",
    "care and maintenance": "C&M",
    "carpenter": "carp",
    "carrier controlled approach": "CCA",
    "carry": "carr",
    "camouflage concealment and deception": "CCD",
    "cartesian coordinate grid": "CCG",
    "cartridge": "cart",
    "casual leave": "C Lve",
    "casualty evacuation": "CASEVAC",
    "categorize": "cat",
    "cathode ray tube": "CRT",
    "cavalry": "cav",
    "central ammunition depot": "CAD",
    "central mechanical transport depot": "CMTD",
    "central officers' record office": "CORO",
    "central ordnance depot": "COD",
    "central processing unit": "CPU",
    "centralize": "cen",
    "centre": "cen",
    "centre of gravity": "CG",
    "centre for naval research and development": "CNRD",
    "certify": "cert",
    "certificate": "cert",
    "channel": "ch",
    "channelize": "ch",
    "chemical warfare": "CW",
    "chemical biological radiological and nuclear": "CBRN",
    "chattogram hill tracts": "CHT",
    "check": "chk",
    "circuit": "cct",
    "circular": "cir",
    "circular error probability": "CEP",
    "civilian": "civ",
    "civil": "civ",
    "civil affairs": "CA",
    "civil military relations": "CMR",
    "class": "cl",
    "classify": "cl",
    "clearance diver": "CD",
    "clearance diving team": "CDT",
    "clear": "clr",
    "clearance": "clr",
    "clerk": "clk",
    "close air support": "CAS",
    "close in weapon system": "CIWS",
    "closest point of approach": "CPA",
    "close quarter battle": "CQB",
    "close quarter combat": "CQC",
    "coastal radar station": "CRS",
    "co-locate": "coloc",
    "column": "colm",
    "combat": "cbt",
    "combat supply": "C sup",
    "combat search and rescue": "CSAR",
    "combat air patrol": "CAP",
    "combat decision making process": "CDMP",
    "combat group": "cbt G",
    "combat team": "cbt T",
    "combat zone": "CZ",
    "combine": "comb",
    "combined anti-submarine exercise": "CASEX",
    "combined military hospital": "CMH",
    "commander": "comd",
    "command": "comd",
    "commandant": "comdt",
    "command and control": "C2",
    "command post exercise": "CPX",
    "command control and communications": "C3",
    "command control communication computer and intelligence": "C4I",
    "commander amphibious task force": "CATF",
    "commander landing force": "CLF",
    "commander in chief": "C in C",
    "commando": "cdo",
    "commitment": "cmt",
    "communication centre": "COMCEN",
    "communication head": "COMHD",
    "communication intelligence": "COMINT",
    "communication plan": "COMPLAN",
    "communication security": "COMSEC",
    "communication zone": "CommZ",
    "company": "coy",
    "comparative statement": "CST",
    "competent financial authority": "CFA",
    "competition": "cmpt",
    "composite": "comp",
    "conct": "concealment",
    "concentrate": "conc",
    "concept of operation": "C of O",
    "conclude": "concl",
    "conclusion": "concl",
    "concentration area": "Conc A",
    "conference": "conf",
    "confidential": "confd",
    "confidentiality": "confd",
    "confirm": "cfm",
    "confirmatory notes": "CN",
    "construct": "constr",
    "contingency": "contg",
    "contingent": "contgt",
    "contingent owned equipment": "COE",
    "continue": "cont",
    "control": "ctrl",
    "control and reporting": "C&R",
    "control zone": "CTZ",
    "convalesce": "convl",
    "conventional": "conv",
    "conventional warfare": "CW",
    "conventional warfare force": "CWF",
    "conversation": "cnsn",
    "concept of composite air operations": "COMAO",
    "condition": "cond",
    "consider": "cons",
    "consideration": "cons",
    "cook": "ck",
    "cooperation": "coop",
    "coordinate": "coord",
    "coronary care unit": "CCU",
    "correction": "corrn",
    "correspondence": "Corres",
    "corrugated galvanized iron": "CGI",
    "counter attack": "C attk",
    "counter countermeasure": "CCM",
    "counter insurgency operation": "CIO",
    "counter intelligence": "C int",
    "counter penetration": "C pen",
    "countermeasure": "CM",
    "course of action": "COA",
    "court of inquiry": "C of I",
    "critical capability": "CC",
    "critical event": "CE",
    "critical requirement": "CR",
    "critical vulnerability": "CV",
    "crossing": "X",
    "cross": "X",
    "cross road": "xrd",
    "crypto centre": "CRYPCEN",
    "culminating point": "cul P",
    "cumulative grade point average": "CGPA",
    "cyber": "cyb",
    "cyber warfare": "cybW",
    "cycle ending exercise": "CEE",

    // D
    "daily maintenance": "DM",
    "dangerously ill": "DI",
    "date": "dt",
    "date-time-group": "DTG",
    "dangerously ill list": "DIL",
    "dead reckoning": "DR",
    "debit voucher": "DV",
    "debussing point": "D pt",
    "decision making process": "DMP",
    "decision support template": "DST",
    "decisive conditions": "DC",
    "decontaminate": "decon",
    "deck decompression chamber": "DDC",
    "deck landing": "DL",
    "defensive counter-air": "DCA",
    "defensive counter air operations": "DCAO",
    "defence committee of the cabinet": "DCC",
    "defender class boat": "DCB",
    "degaussing": "DG",
    "degree": "Deg",
    "deliberate decision making process": "DDMP",
    "deliver": "del",
    "demand": "dmd",
    "demi-official": "DO",
    "demolish": "dml",
    "demonstrate": "demo",
    "department": "dept",
    "departmental": "dept",
    "deploy": "depl",
    "deputy": "Dy",
    "designate": "des",
    "destroyer": "DD",
    "detach": "det",
    "detachment ground study section": "DGSS",
    "develop": "dev",
    "diagram": "diag",
    "diesel oil": "dieso",
    "difference": "diff",
    "different": "diff",
    "directing staff": "DS",
    "direct support": "DS",
    "director": "Dir",
    "director engineers": "D Engrs",
    "directorate": "dte",
    "director general": "DG",
    "directorate general defence purchase": "DGDP",
    "directorate general forces intelligence": "DGFI",
    "directorate general medical service": "DGMS",
    "disadvantage": "disadv",
    "disaster management": "DM",
    "disbursement": "disb",
    "discipline": "discip",
    "discussion": "disc",
    "disengagement": "disengt",
    "dispersal": "disp",
    "dispersal area": "Disp A",
    "disposition": "disposn",
    "distance": "dstn",
    "distance measuring equipment": "DME",
    "distribution": "distr",
    "district": "dist",
    "division": "div",
    "divisional administrative area": "DAA",
    "docking and essential defects": "DED",
    "dockyard": "dyd",
    "dockyard and engineering workshop": "DEW",

    // E
    "earmark": "emk",
    "east bengal": "EB",
    "echelon": "ech",
    "economy": "econ",
    "education training grant": "ETG",
    "educational": "edn",
    "education": "edn",
    "effective": "eff",
    "effect": "eff",
    "effect based operation": "EBO",
    "effective sonar range": "ESR",
    "electronic emission control": "EMCON",
    "electrical": "L",
    "electrical and mechanical": "E&M",
    "electro magnetic pulse": "EMP",
    "electronic protection measure": "EPM",
    "electronic warfare support measure": "ESM",
    "electronic counter countermeasures": "ECCM",
    "electronic countermeasures": "ECM",
    "electronic flight instrument system": "EFIS",
    "electronic intelligence": "ELINT",
    "emergency locator transmitter": "ELT",
    "engine maintenance manual": "EMM",
    "electronic order of battle": "EOB",
    "element": "elm",
    "embark": "emb",
    "embussing point": "EP",
    "emergency": "emg",
    "emplace": "empl",
    "employ": "emp",
    "enclose": "encl",
    "enemy": "en",
    "engagement": "engt",
    "engagement area": "EA",
    "engine": "eng",
    "engineer": "engr",
    "engineer construction battalion": "ECB",
    "engineering": "engg",
    "envelope": "env",
    "environment": "envt",
    "equipment": "eqpt",
    "equivalent": "eqvt",
    "essential elements of information": "EEI",
    "essential elements of friendly information": "EEFI",
    "establish": "estb",
    "estimate": "est",
    "evacuate": "evac",
    "evaluate": "eval",
    "event template": "EVENTEMP",
    "examine": "exam",
    "exchange": "exch",
    "exclude": "excl",
    "exclusive economic zone": "EEZ",
    "execute": "exec",
    "exercise": "ex",
    "exfiltration": "exfil",
    "expedite": "xpd",
    "explanation": "expln",
    "expenditure": "exp",
    "explosive": "expl",
    "explosion": "expl",
    "explosive ordnance disposal": "EOD",
    "explosive reactive armour": "ERA",
    "extend": "ext",
    "extension": "ext",
    "external": "extl",
    "extra regimental employment": "ERE",
    "excess defence articles": "EDA",
    "estimated time of arrival": "ETA",
    "estimated time of completion": "ETC",
    "estimated time of departure": "ETD",

    // F
    "facsimile": "FAX",
    "favourable air situation": "FAS",
    "fast attack craft": "FAC",
    "fast motor boat": "FMB",
    "fast patrol boat": "FPB",
    "feet of fresh water": "FFW",
    "feet of sea water": "FSW",
    "forward repair and recovery team": "FRRT",
    "field": "fd",
    "field general court-martial": "FGCM",
    "field intelligence service": "FIS",
    "field intelligence unit": "FIU",
    "field of fire": "F of F",
    "field post office": "FPO",
    "field service marching order": "FSMO",
    "field service regulations": "FSR",
    "field surgical team": "FST",
    "field training exercise": "FTX",
    "fighter controller training unit": "FCTU",
    "fighter engagement zone": "FEZ",
    "fighter ground attack": "FGA",
    "fighter reconnaissance": "FR",
    "fighting": "ftg",
    "fight": "ftg",
    "figure": "fig",
    "final handling test": "FHT",
    "finance": "fin",
    "financial year": "FY",
    "fire and move": "F and M",
    "fire control data computer": "FCDC",
    "fire control equipment": "FCE",
    "fire control director": "FCD",
    "fire control instrument": "FCI",
    "fire control radar": "FCR",
    "fire control system": "FCS",
    "fire fighting": "F/F",
    "fire support coordination centre": "FSCC",
    "fire support coordination line": "FSCL",
    "fire support coordination measures": "FSCM",
    "fire support plan": "FSP",
    "fixed decompression chamber": "FDC",
    "fixed wing": "FW",
    "fleet maintenance group": "FMG",
    "fleet orders": "FO",
    "flight": "flt",
    "flight level": "FL",
    "flying": "flg",
    "flying instructor course": "FIC",
    "folding boat equipment": "FBE",
    "follow": "fol",
    "foot": "ft",
    "feet": "ft",
    "formation": "fmn",
    "forming-up place": "FUP",
    "forward": "fwd",
    "forward air base": "FAB",
    "forward aiming and refueling point": "FARP",
    "forward air support operations centre": "FASOC",
    "forward airhead maintenance area": "FAMA",
    "forward assembly area": "FAA",
    "forward combat zone": "FCZ",
    "forward control post": "FCP",
    "forward defended locality": "FDL",
    "forward edge of battle area": "FFBA",
    "forward line of enemy troops": "FLET",
    "forward line of own troops": "FLOT",
    "forward logistic base": "FLB",
    "forward maintenance area": "FMA",
    "forward operating base": "FOB",
    "forward ordnance depot": "FOD",
    "forward repair team": "FRT",
    "fragment": "frag",
    "fragmentary order": "FragO",
    "free fire zone": "FFZ",
    "fresh ration allowance": "FRA",
    "fresh water": "FW",
    "friendly aircraft movement": "FAM",
    "friendly forces information requirements": "FFIR",
    "function": "func",
    "functional check flight": "FCF",
    "furnace fuel oil": "FFO",
    "furthest-on circles": "FOC",

    // G
    "gallon per minute": "gpm",
    "garrison": "gar",
    "garrison duty officer": "GDO",
    "garrison engineer": "GE",
    "general court martial": "GCM",
    "general duties": "GD",
    "general list": "GL",
    "general operations plot": "GOP",
    "general purpose machine gun": "GPMG",
    "general staff": "GS",
    "general transport": "GT",
    "generalize": "gen",
    "geographical reference system": "GEOREF",
    "global positioning system": "GPS",
    "government": "govt",
    "government order": "GO",
    "grade point average": "GPA",
    "grenade": "gren",
    "ground": "grd",
    "ground based air defence": "GBAD",
    "ground controlled approach": "GCA",
    "ground controlled interception": "GCI",
    "ground support equipment": "GSE",
    "ground power unit": "GPU",
    "ground zero": "GZ",
    "group": "gp",
    "guard": "gd",
    "guided missile": "GM",
    "gun controller": "GC",

    // H
    "harbour": "har",
    "head": "hd",
    "headquarters": "HQ",
    "height": "ht",
    "helicopter": "heli",
    "high density airspace control zone": "HIDACZ",
    "high explosive anti-tank": "HEAT",
    "high explosive": "HE",
    "high frequency": "HF",
    "hospital": "hosp",
    "horse power": "HP",
    "high power": "HP",
    "hour": "hr",
    "hours": "hr",

    // I
    "identification friend or foe": "IFF",
    "identify": "ident",
    "identity card": "ID",
    "illuminate": "illum",
    "immediate": "imm",
    "important": "imp",
    "importance": "imp",
    "improvised explosive device": "IED",
    "include": "incl",
    "incorporate": "incorp",
    "increase": "incr",
    "independent": "indep",
    "infantry": "inf",
    "information": "info",
    "information technology": "IT",
    "infra-red": "IR",
    "inspection": "insp",
    "install": "instl",
    "instruct": "instr",
    "intelligence": "Int",
    "intelligent": "Int",
    "internal": "itrl",
    "international": "intl",
    "investigation": "invstg",
    "issue voucher": "IV",

    // J-Z (Selected Key Abbreviations)
    "joint": "jt",
    "joint force": "JF",
    "joint forces headquarters": "JFHQ",
    "killed in action": "KIA",
    "killing zone": "KZ",
    "kilometer": "km",
    "landing area": "LA",
    "landing craft": "LC",
    "leave": "lve",
    "letter": "ltr",
    "level": "lvl",
    "lieutenant": "Lt",
    "light machine gun": "LMG",
    "line of control": "LOC",
    "logistics": "log",
    "machine gun": "MG",
    "maintain": "maint",
    "maintenance": "maint",
    "major": "maj",
    "manage": "mng",
    "management": "mgt",
    "medical": "med",
    "memorandum": "memo",
    "military": "mil",
    "ministry of defence": "MOD",
    "mission": "msn",
    "movement": "mov",
    "movement order": "MovO",
    "national": "ntl",
    "necessary": "nec",
    "nothing to report": "NTR",
    "number": "no",
    "objective": "obj",
    "observation post": "OP",
    "officer": "offr",
    "officer in charge": "OIC",
    "operation": "op",
    "operational": "op",
    "operation order": "OpO",
    "organize": "org",
    "paragraph": "para",
    "personal assistant": "PA",
    "petroleum oil and lubricants": "POL",
    "position": "posn",
    "precedence": "prec",
    "prepare": "prep",
    "president": "pres",
    "priority": "pri",
    "prisoner of war": "POW",
    "private": "pte",
    "problem": "prob",
    "procedure": "proc",
    "programme": "prog",
    "project": "proj",
    "quartermaster": "QM",
    "reconnaissance": "recce",
    "reference": "ref",
    "regiment": "regt",
    "reinforcement": "rft",
    "release": "rel",
    "replacement": "repl",
    "report": "rep",
    "request": "req",
    "requirement": "reqr",
    "reserve": "res",
    "restricted": "restd",
    "retired": "retd",
    "return to base": "RTB",
    "road": "rd",
    "route": "rte",
    "routine": "rtn",
    "salvage": "sal",
    "satellite": "sat",
    "search and rescue": "SAR",
    "second in command": "2IC",
    "secretary": "secy",
    "sector": "sec",
    "security": "sy",
    "senior": "sr",
    "service": "svc",
    "signal": "sig",
    "signature": "sign",
    "situation": "sit",
    "situation report": "SITREP",
    "special": "spl",
    "specify": "spec",
    "speed": "spd",
    "squadron": "sqn",
    "standing operating procedure": "SOP",
    "station": "sta",
    "subject": "subj",
    "submarine": "SS",
    "supply": "sup",
    "support": "sp",
    "tactical": "tac",
    "tactical headquarters": "Tac HQ",
    "target": "tgt",
    "technical": "tech",
    "telephone": "tel",
    "temperature": "temp",
    "temporary": "ty",
    "time zone": "TZ",
    "training": "trg",
    "transmission": "tx",
    "transport": "tpt",
    "unclassified": "uncl",
    "under command": "UC",
    "urgent": "urg",
    "utilize": "ut",
    "vehicle": "veh",
    "velocity": "vel",
    "warning": "wng",
    "warning order": "WngO",
    "weapon": "wpn",
    "withdraw": "wdr",
    "work order": "WkO",
    "workshop": "wksp",
    "wounded in action": "WIA",
    "zone": "zn"
};

// Map abbreviations back to their array of meanings (multiple meanings support)
const MIL_DEABBREVIATIONS = {};
for (const [meaning, abbr] of Object.entries(MIL_ABBREVIATIONS)) {
    const key = abbr.toLowerCase();
    if (!MIL_DEABBREVIATIONS[key]) {
        MIL_DEABBREVIATIONS[key] = [];
    }
    // Capitalize the first letter of each word in meaning for display
    const formattedMeaning = meaning.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
    if (!MIL_DEABBREVIATIONS[key].includes(formattedMeaning)) {
        MIL_DEABBREVIATIONS[key].push(formattedMeaning);
    }
}

// Add the explicit multiple meanings from the manual JSSDM Annex B
const JSP_MULTIPLE_MEANINGS = {
    "aa": ["Avenue of Approach", "Anti-Aircraft"],
    "ab": ["Airborne", "After Burner"],
    "ad": ["Air Defence", "Despatch"],
    "ada": ["Air Defence Area", "Action Data Automation", "Air Defence Alert"],
    "ads": ["Advanced Dressing Station", "Air Despatch Service"],
    "agl": ["Above Ground Level", "Automatic Grenade Launcher"],
    "ai": ["Air Intelligence", "Air Interception", "Air Interdiction", "Artificial Intelligence"],
    "aib": ["Army Instruction Bangladesh", "Air Investigation Board"],
    "alo": ["Air Liaison Officer", "Air Electrical Officer"],
    "a/m": ["Above mentioned", "Aforementioned"],
    "am": ["Amplitude Modulated", "Amplitude Modulation"],
    "ama": ["Army Maintenance Area", "Airhead Maintenance Area"],
    "aobc": ["Armoured Officers Basic Course", "Artillery Officers Basic Course"],
    "aor": ["Area of Responsibility", "Aircraft Occurrence Report"],
    "ap": ["Ammunition Point", "Air Publication", "Armed Police", "Armour Piercing"],
    "appr": ["Appropriately", "Appropriation"],
    "at": ["Animal Transport", "Air Transport"],
    "atd": ["Actual Time of Departure", "Army Training Directive"],
    "ati": ["Army Training Instruction", "Annual Technical Inspection"],
    "auto": ["Automatic", "Automatically", "Automation"],
    "aval": ["Available", "Availability"],
    "baa": ["Brigade Administrative Area", "Bangladesh Army Act"],
    "bb": ["Bir Bikram", "Baily Bridge", "Battleship"],
    "bcc": ["Basic Commando Course", "Basic Conversion Course"],
    "bd": ["Bomb Disposal", "Battle Dress"],
    "bf": ["Bring Forward", "Brought Forward"],
    "bl": ["Bill of Lading", "Bomb Line"],
    "br": ["Book of Reference", "Bangladesh Railway"],
    "br": ["Bridge", "Branch"],
    "bldg": ["Building", "Build"],
    "cas": ["Casual", "Casualty"],
    "cb": ["Counter Bombardment", "Charge Book", "Circuit Breaker"],
    "cc": ["Contingent Commander", "Cruiser", "Compensatory Chance"],
    "ccp": ["Casualty Collection Point", "Casualty Collection Post"],
    "cg": ["Centre of Gravity", "Guided Missile Cruiser"],
    "ci": ["Chief Instructor", "Counter Insurgency"],
    "civ": ["Certificate", "Certified Issue Voucher"],
    "cl": ["Confinement to Lines", "Civil Liaison", "Light Cruiser"],
    "clf": ["Commander Land Forces", "Landing Force"],
    "clk": ["Clerk", "Clerical"],
    "clo": ["Clothe", "Cloth"],
    "coa": ["Course of Action", "Committee of Adjustment"],
    "comm": ["Communicate", "Communication"],
    "cp": ["Command Post", "Critical Point"],
    "cr": ["Casualty Return", "Central Register"],
    "crv": ["Certificate", "Certified Receipt Voucher"],
    "crypto": ["Cryptographer", "Cryptography"],
    "cs": ["Call sign", "Commando Ship"],
    "ct": ["Covering Troops", "Currency Training", "Counter Terrorism"],
    "cv": ["Aircraft Carrier", "Combat Vehicle", "Command Vehicle"],
    "da": ["Defence Attache", "Drafting Authority", "Distributing Authority", "Daily Allowance"],
    "def": ["Defend", "Defense"],
    "dep": ["Depot", "Depart"],
    "df": ["Defensive Fire", "Direction Finding"],
    "dfc": ["Deficiency", "Deficient"],
    "dg": ["Director General", "Degaussing", "Danger Good"],
    "dh": ["Decision Height", "Direct Hit"],
    "diff": ["Differ", "Different"],
    "div": ["Divide", "Division"],
    "dm": ["Daily Maintenance", "Disaster Management"],
    "dma": ["Daily Maintenance Allowance", "Daily Messing Allowance", "Divisional Maintenance Area"],
    "dp": ["Distribution Point", "Delivery Point", "Dumping Point", "Decision Point"],
    "dr": ["Despatch Rider", "Discrepancy Report"],
    "ds": ["Directing Staff", "Direct Support", "Deputy Secretary"],
    "dst": ["Decision Support Template", "Director of Supply and Transport"],
    "dvr": ["Driver", "Driving"],
    "dz": ["Drop Zone", "Danger Zone"]
};

// Merge multiple meanings to ensure correctness
for (const [abbr, meanings] of Object.entries(JSP_MULTIPLE_MEANINGS)) {
    MIL_DEABBREVIATIONS[abbr.toLowerCase()] = meanings;
}
